name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.x.x
      - name: pnpm install
        run: |
          pnpm install
      - name: lint
        run: |
          pnpm lint
      - name: run package commands
        run: |
          pnpm run command
